language: node
script:
  - yarn
  - yarn deploy
env:
  global:
    aws_access_key_id: AKIAJC5ZIUINOWH7ARRA
    secure: l3+LWIPrkvUQ0PhVhlkzDRfDy0sOXyjPWoZEM9XoeQpN4Lyhrct4Aad2LTrAE+E6iks0PEVaG8NAtIqzBf8lgxylUjlkzsjWwH1Tf2trHD8m6pdhFe4DvEMGYTtG1PGsyn4mVV3Fo8AP1xx9RdKEq5aZFzEuA2j6VjI66I3fGwSgx4kqxzPnZhgwD+oR/YFjLubdGer2KcAHZSjMd3OO04dU8U8K279RQ/Spx/0bMVvpx1ZG44n6FaVugvUuWC6IyrKsIlZnHfcAnrqPm2ZUUexHsORwr/ENw7XJlffrvO7JXfUBpkoKV8paX2MHWD84u/Gr/v9Db0fdZtXSjdC8DLZ541zRYBqAV/S5tsg0E0uVVa01b1OskoeRQcywDpzwU1T7GzFVti+u2w/fj85W+Gg0IcWR2k8FaXofXeywQAnzx5FMWFmxZdaOSpDnlceYQclyQeW5fuhP066kykwAw4BTBIJSonUsz585KJj77A0lS+7zZkkJDeqmwZBQNTIi+b95Ljtuk04TMWyaZWgyqd6X+WiqIphkkvSLz9t/LVoGo+cOEciaLNLpmvxbwvCrTn1twkI+JdMT8KB8LHzZmh2sDODq8tW71XWdUFM83GqVVxNJ/p33VwZHKuDx9F2dhTElRapgN+f1u8Yb78JkuMqIbIdLXtz8H9L0Psr4vjU=
